### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by vatterspun** [sintaxasn/EncodeHD#3]
I noticed there wasn't a license for EncodeHD.  I don't know if anyone's referencing your code but just in case, any chance I could get you to use something for the program beyond standard copyright?  Maybe just MIT or Apache 2.0?

**Comment by sintaxasn** [comment]
Hey there. Added the GPLv3 License - this is required due to a reliance on FFmpeg, Atomic Parsley and MP4Box

Cheers, Dan
